### ISSUE TITLE
[vue-erdjs@1.0.0-vue3-erdjs11-rc2] vue-erdjs-demo run issue

### ISSUE THREAD

**Issue by NiftyWell** [stephaneLeroy/vue-erdjs#5]
Hello, I have a problem when launching the vue-erdjs-demo project with vue-erdjs@1.0.0-vue3-erdjs11-rc2

```
Forced re-optimization of dependencies
error when starting dev server:
Error: Failed to resolve entry for package "vue-erdjs". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:34380:11)
    at resolvePackageEntry (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:34377:5)
    at tryNodeResolve (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:34135:20)
    at Context.resolveId (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:33937:28)
    at Object.resolveId (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:35184:55)
    at async file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:62424:21
    at async addManuallyIncludedOptimizeDeps (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:36994:31)
    at async createDepsOptimizer (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:36195:9)
    at async initDepsOptimizer (file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:36117:9)
    at async file:///home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo/node_modules/vite/dist/node/chunks/dep-561c5231.js:59135:17
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: vue-erdjs-demo@0.0.0 
npm ERR!   at location: home/my_user/Documents/Vue-3/vue-erdjs-vue3-migration/vue-erdjs-demo 
```
main/module/exports of vue-erdjs:

```json
"main": "./dist/index.umd.js",
"module": "./dist/index.es.js",
"exports": {
    ".": {
        "import": "./dist/index.es.js",
        "require": "./dist/index.umd.js"
    },
    "./dist/index.css": "./dist/index.css",
    "./vite/vite.config.node.js": "./vite/vite.config.node.js"
},
```
Ubuntu 20.04.4 LTS
vue-erdjs@1.0.0-vue3-erdjs11-rc2
nodejs v16.17.1 
npm 8.19.2

**Comment by stephaneLeroy** [comment]
Hello,

This is a monorepo. You have to build the library first before launching the demo.
`
npm run lib:build
npm run demo:dev
`

I added an npm target to avoid this type of problem. Now you just have to run :
`
npm run demo
`

Let me know if you still have an issue.
